### ISSUE TITLE
[Prerequisite] Complete 3B1B Neural Networks Playlist

### ISSUE THREAD

**Issue by himanshu-02** [virajbshah/rl-inator#2]
Close this issue when both of you are done with the [Neural Networks Playlist](https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi) and make sure to commit your notes in your respective branch as well! Once done, add the [commit id](https://stackoverflow.com/questions/8910271/how-can-i-reference-a-commit-in-an-issue-comment-on-github) prior to closing it.

**Comment by Anushka-1007** [comment]
Neural Networks completed

#7d7d909f3b326974ef3cd9b8ab92120f1b03babb

**Comment by Anushka-1007** [comment]
Neural Networks Completed

# 7d7d909f3b326974ef3cd9b8ab92120f1b03babb
